styx, in progress
on kontext-dev, I run into the following error:
$ treex -q -Lcs Read::CoNLLlike format=styx1.0 from=../input/train-1.o Write::ManateeGeneral format=styx1.0
You can only consume roles, MooseX::Getopt is not a Moose role at /usr/local/lib/perl/5.18.2/Moose/Exporter.pm line 419
        Moose::with('MooseX::Getopt') called at /home/vernerova/Treex/lib/Treex/Core/Run.pm line 9
        require Treex/Core/Run.pm at /home/vernerova/Treex/bin/treex line 5
        main::BEGIN at /home/vernerova/Treex/lib/Treex/Core/Run.pm line 0
        eval {...} at /home/vernerova/Treex/lib/Treex/Core/Run.pm line 0
Compilation failed in require at /home/vernerova/Treex/bin/treex line 5.
BEGIN failed--compilation aborted at /home/vernerova/Treex/bin/treex line 5.